Zimbra/zm-admin-console

WebRoot/js/zimbraAdmin/statistics/view/ZaGlobalAdvancedStatsPage.js
- fix issue where message volume and chart are not getting generated for multinode environment
- check if object exists before using it
Testing notes:
1) check with customer data
- copied rrd files from ticket to /opt/zimbra/logger/db/data
- restart mail server
- check if charts are generated in admin console
2) check with own server data
- revert back rrd files to earlier ones from /opt/zimbra/logger/db/data
- restart mail server
- check if charts are generated in admin console
=> ZCS-1660 message count and message chart volume show nothing

WebRoot/js/zimbraAdmin/accounts/view/ZaAccountXFormView.js
ZCS-1666 C - Bug 107948 - Persistent XSS - mail addrs [CWE-79] 
Issue: XSS vulnerability in Admin Console account alias section.
Fix: HTML encoding the alias values at display level.
Changeset:
* ZaAccountXFormView.js:
* Adding getDisplayValue() definition for aliases tab to set the HTML encoded values on ui.
* ZaAccountXFormView::aliasSelectionListener(): HTML decoding the aliases display values so that the cached account level values are not saved as HTML encoded.
=> ZCS-1666 C - Bug 107948 - Persistent XSS - mail addrs [CWE-79]

WebRoot/js/zimbraAdmin/accounts/view/ZaAccountMemberOfListView.js
Issue: The new Dl dialog shows “Loading” for direct/indirect member list view.
Expected: As its a case of new Dl, there would be nothing to load and thus should be empty widget without a loading text.
Changeset:
*  ZaAccountMemberOfListView.js: Setting the msg variable values as empty string instead of “Loading”.
=> ZCS-1638 New DL : direct member of field always shows 'Loading' text

WebRoot/js/zimbraAdmin/ZaZimbraAdmin.js, WebRoot/js/zimbraAdmin/accounts/controller/ZaAccountListController.js, WebRoot/js/zimbraAdmin/accounts/view/DeleteAcctsPgrsDlg.js, WebRoot/js/zimbraAdmin/accounts/view/MoveAliasXDialog.js, WebRoot/js/zimbraAdmin/accounts/view/ZaAccountXFormView.js, WebRoot/js/zimbraAdmin/common/ZaActionStatusView.js, WebRoot/js/zimbraAdmin/common/ZaController.js, WebRoot/js/zimbraAdmin/common/ZaCurrentAppBar.js, WebRoot/js/zimbraAdmin/common/ZaErrorDialog.js, WebRoot/js/zimbraAdmin/common/ZaItem.js, WebRoot/js/zimbraAdmin/common/ZaTreeItem.js, WebRoot/js/zimbraAdmin/cos/controller/ZaCosListController.js, WebRoot/js/zimbraAdmin/cos/model/ZaCos.js, WebRoot/js/zimbraAdmin/cos/view/ZaCosXFormView.js, WebRoot/js/zimbraAdmin/cos/view/ZaNewCosXWizard.js, WebRoot/js/zimbraAdmin/dl/model/ZaDistributionList.js, WebRoot/js/zimbraAdmin/dl/view/ZaDLXFormView.js, WebRoot/js/zimbraAdmin/dl/view/ZaNewDLXWizard.js, WebRoot/js/zimbraAdmin/domains/controller/ZaDomainController.js, WebRoot/js/zimbraAdmin/domains/controller/ZaDomainListController.js, WebRoot/js/zimbraAdmin/domains/model/ZaDomain.js, WebRoot/js/zimbraAdmin/domains/view/ZaNewDomainXWizard.js, WebRoot/js/zimbraAdmin/globalconfig/view/GlobalConfigXFormView.js, WebRoot/js/zimbraAdmin/resource/view/ZaResourceXFormView.js, WebRoot/js/zimbraAdmin/search/view/ZaSearchBubbleList.js, WebRoot/js/zimbraAdmin/search/view/ZaSearchField.js, WebRoot/js/zimbraAdmin/servers/view/ZaServerVolumesListView.js
Issue:
- Previous fixes of XSS prevented XSS attack from admin console as it modified data before saving, but this will not prevent XSS attack where data is set using zmprov
Resolution:
- revisited fixes done as part of https://bugzilla.zimbra.com/show_bug.cgi?id=103997, https://bugzilla.zimbra.com/show_bug.cgi?id=104777, https://bugzilla.zimbra.com/show_bug.cgi?id=104413, https://bugzilla.zimbra.com/show_bug.cgi?id=104414, https://bugzilla.zimbra.com/show_bug.cgi?id=104791
- previous fixes were modifying data in the model itself, which created lot of issues where we were saving &amtp;gt; and &amtp;lt; instead of < and > symbols in database
- ideally XSS should be handled at view layer only so whenever we show data which can have scripts then html encode it before showing, we should never …
=> ZCS-1667 XSS Issues

.gitignore, WebRoot/js/zimbraAdmin/ZaZimbraAdmin.js, WebRoot/public/Docs.jsp, WebRoot/public/admin.jsp, WebRoot/public/proto/index.jsp, build.xml, ivy.xml
zm-admin-console:ivy.xml
- add dependency on zm-timezones repo
zm-admin-console:build.xml
- change timezones target to get published zip from zm-timezones repo
- extract timezone files from zip and copy to appropriate locations
- templates and timezones target are already defined as dependencies for jam-files target so no need to explicitly call those targets
=> ZCS-1661 Use zip published by zm-timezones repo to get timezone data

Readme.md, build.xml, ivy.xml
ZCS-1326: Create separate versions of zm-ajax for zm-web-client & zm-admin-console
Description: Changes to use zm-admin-ajax instead of zm-ajax.
Changeset:
* build.xml:
* Updating references to point to zm-admin-ajax, instead of zm-ajax.
* Removing obsolete target build-ajax.
* ivy.xml: Updating dependency to use zm-admin-ajax.
* Renaming Readme.txt to Readme.md to support markdown syntax.
* Updating Readme file to document zm-admin-ajax instead of zm-ajax.
=> ZCS-1326 Create separate versions of zm-ajax for zm-web-client & zm-admin-console

build.xml
- fix of https://github.com/Zimbra/zm-web-client/pull/110#discussion_r131870886
introduced a change which broke dev setup
- for dev setup, we will copy timezone files after deploying webapp and extracti
ng it
=> ZCS-2282 Build script changes for deploying timezone files in dev setup

WebRoot/js/zimbraAdmin/ZaZimbraAdmin.js, WebRoot/js/zimbraAdmin/config/settings/ZaSettings.js, WebRoot/js/zimbraAdmin/domains/controller/ZaDomainListController.js
ZCS-2756: Domain admin is unable to view domain list
ZCS-2757: domain list view is blank when DA has 'AdminConsoleCosRights' on global target
Root cause: 
* `ZaZimbraAdmin.hasGlobalDomainListAccess()` was checking rights  using ZaCos object which is not having RIGHT_LIST_DOMAIN attribute.
Fix Description:
* Fixing check for rights check for domain to check ZaDomain object for RIGHT_LIST_DOMAIN permission.
=> ZCS-2756: Domain admin is unable to view domain list, ZCS-2757: domain list view is blank when DA has 'AdminConsoleCosRights' on global target

WebRoot/js/zimbraAdmin/common/Super_XFormItems.js
- introduce way to clear visibility/disability checks on individual elements when composite element has those checks already defined
=> ZCS-2968 "Enable S/MIME public key encryption and signing" cannot be shown on delegated admin

WebRoot/js/zimbraAdmin/ZaZimbraAdmin.js
- When zimbraHelpAdminURL is set in global config, admin console was ignoring that value
- Add code to get url value from global config also if it is not set at domain level
=> ZCS-3487 zimbraHelpAdminURL not working when set in global config

build.xml
Admin console is not working as it is not able to find timezones zip after changes done in https://github.com/Zimbra/zm-timezones/commit/7059681ac1fc2093ebb6ea93241a9fe6d98e7b3e, so fixing that issue
=> Fix admin console build

WebRoot/js/zimbraAdmin/mta/view/ZaMTAXFormView.js
Increasing the default width of the column for the queue IDs in the
summary of e-mail messages to display long queue IDs without the need to
resize the column manually.
=> MTA mail queue console: Postfix long queue IDs support

WebRoot/js/zimbraAdmin/mta/view/ZaMTAXFormView.js
The table displaying the summary of messages in the mail queue
management console has got 9 columns in the header row and 8 in the data
rows.
Removed the trailing column in the header row since it skews alignment
and handling of the table in general
=> MTA Mail queue console: removed extra header column

WebRoot/js/zimbraAdmin/mta/view/ZaQMessagesListView.js
Column displaying source domain data in the message summary not
populated at all. Fixed.
=> MTA mail queue console: column with source domain not filled with data

WebRoot/js/zimbraAdmin/mta/model/ZaMTA.js
Error messages from the MTA can be very long, sometimes exceeding the
screen width when displayed in tooltips.
The commits introduces wrapping of long texts, with a visual indentation for
continuation lines.
=> MTA mail queue console: wrapping long MTA error messages in tooltips

WebRoot/js/zimbraAdmin/common/ZaItem.js
**Background:**
- When zimbraLdapGentimeFractionalSecondsEnabled is TRUE, timestamp like zimbraCreateTimestamp is saved in "yyyyMMddHHmmss.SSSZ" format.
- When zimbraLdapGentimeFractionalSecondsEnabled is FALSE, timestamp is saved in "yyyyMMddHHmmss.Z" format.
**Problem:**
If a timestamp has millisecond, datetime is shown without considering client's timezone on Admin Console. (i.e. it is always shown in UTC.)
**Route Cause:**
Timestamp was parsed in the following way:
ZaItem.formatServerTime = function(serverStr) {
if(serverStr) {
var ajxTKServerStr = serverStr.substring(0,8) + "T" + serverStr.substring(8) ;
var curDate = AjxDateUtil.parseServerDateTime(ajxTKServerStr);    
var formatter = AjxDateFormat.getDateTimeInstance(AjxDateFormat.LONG) ;
return formatter.format(curDate) ;
} else { …
=> ZBUG-830: removed millisec from timestamp before parsing it

WebRoot/js/zimbraAdmin/ZaZimbraAdmin.js, WebRoot/js/zimbraAdmin/common/ZaCrtAppTreeHeader.js, WebRoot/js/zimbraAdmin/common/ZaOverviewPanelController.js, WebRoot/js/zimbraAdmin/common/ZaTree.js
Fixing a typo in the method name
=> Typo fix: getHisotryMgr() -> getHistoryMgr()

WebRoot/js/zimbraAdmin/globalconfig/controller/ZaGlobalConfigViewController.js
Consider localhost as valid url.
And don't proceed to verify valid IPV4 in case of localhost.
=> ZBUG-1556 : Fix Ephemeral BackendURL issue.

WebRoot/js/zimbraAdmin/accounts/controller/ZaAccountViewController.js, WebRoot/js/zimbraAdmin/accounts/model/ZaAccount.js, WebRoot/js/zimbraAdmin/accounts/view/ZaAccountXFormView.js, WebRoot/js/zimbraAdmin/accounts/view/ZaNewAccountXWizard.js, WebRoot/js/zimbraAdmin/cos/controller/ZaCosController.js, WebRoot/js/zimbraAdmin/cos/model/ZaCos.js, WebRoot/js/zimbraAdmin/cos/view/ZaCosXFormView.js, WebRoot/js/zimbraAdmin/cos/view/ZaNewCosXWizard.js, WebRoot/messages/ZaMsg.properties
Added facility to alter these attributes.
zimbraFileUploadBlockedFileTypes - Commonly blocked file types for uploading.
zimbraFeatureFileTypeUploadRestrictionsEnabled - Enable/Disable blocked file types set in zimbraFileUploadBlockedFileTypes for uploading.
These attributes are availble at account and cos levels.
=> ZCS-10415 : Allow admin to configure disallowed attachment types.

WebRoot/js/zimbraAdmin/common/ZaAuthenticate.js, WebRoot/js/zimbraAdmin/common/ZaController.js, WebRoot/js/zimbraAdmin/common/ZaLoginDialog.js
Must change password (zimbraPasswordMustChange) was not working due to JS error.
Parameter mismatch was the reason for the fatal JS errors.
Fix the parameters with different login scenarios.
=> ZBUG-2457 : Fix 'Must change password' issue.

WebRoot/js/zimbraAdmin/common/ZaController.js
Username field should not remain disabled when server throws AUTH_EXPIRED exception.
This issue surfaces with refactored admin 2fa flow on back-end.
=> ZCS-11022 : Fixed disabled username field.

WebRoot/js/zimbraAdmin/servers/model/ZaServer.js, WebRoot/js/zimbraAdmin/servers/view/ZaEditVolumeXDialog.js
UX improvements for volume management view:
The user should only be able to edit an external volume's name.
Internal volume editing should remain the same.
Current volume selection dropdown width should be greater (index, primary and secondary)
=> ZCS-11809: UX improvements for volume management

WebRoot/js/zimbraAdmin/accounts/controller/ZaAccountViewController.js, WebRoot/js/zimbraAdmin/accounts/model/ZaAccount.js, WebRoot/js/zimbraAdmin/accounts/view/ZaAccountXFormView.js, WebRoot/js/zimbraAdmin/accounts/view/ZaNewAccountXWizard.js, WebRoot/js/zimbraAdmin/cos/controller/ZaCosController.js, WebRoot/js/zimbraAdmin/cos/model/ZaCos.js, WebRoot/js/zimbraAdmin/cos/view/ZaCosXFormView.js, WebRoot/js/zimbraAdmin/cos/view/ZaNewCosXWizard.js, WebRoot/messages/ZaMsg.properties
Commented code to hide UI components so that it can be used when the feature is re-implemented (ZCS-11977).
=> ZCS-11974: Remove UI for filetype restrictions 

WebRoot/js/zimbraAdmin/servers/view/ZaEditVolumeXDialog.js
This solution intends to hide the following internal-volume-specific fields when editing an external volume:
1. ZaServer.A_VolumeCompressBlobs
2. ZaServer.A_VolumeCompressionThreshold
The existing _enableDisableChecks_ attribute was replaced with _visibilityChecks_ for the mentioned fields.
=> ZCS-12008: Compress Blobs and Compression threshold should not be visible on S3 Edit volume UI

WebRoot/js/zimbraAdmin/servers/view/ZaEditVolumeXDialog.js
Implementation:
For admin console storage management tabs under server, implemented the following:
Compression blobs(CB) and compression threshold(CT) are dependent on each other i.e. the based on value of CB user will be able to edit the value of CT.
Its applicable only for internal Volumes while adding and editing.
If the value of CB is false the CT value displayed to the user would be "-"
If the value of CB is true the CT value displayed to the user would be one that is provided by the user.
=> ZCS-12396:Implemented dependency of compress blobs and compress threshold while adding and editing the internal volume

WebRoot/js/zimbraAdmin/globalconfig/model/ZaGlobalConfig.js, WebRoot/js/zimbraAdmin/search/model/ZaSearch.js
**Problem:**
When millions of accounts exist on the system and CountObjectsRequest with userAccount type is sent from Admin Console to a server, it causes high load on a ldap server.
**Fix:**
Intoduced Ldap attr to enable/disable the counting of userAccount in CountObjectsRequest
**Test-cases:**
1. when zimbraCountObjectsEnabled is TRUE
send CountObjectsRequest with account or userAccount type.
show number of accounts in Home -> Summary -> Accounts and Manage -> left pane -> the number of accounts
2. when zimbraCountObjectsEnabled is FALSE
not to send CountObjectsRequest with account or userAccount type.
show N/A in Home -> Summary -> Accounts and Manage -> left pane -> the number of accounts
=> ZCS-12966 Enable/Disable CountObjectsRequest with userAccount/account type on Zimbra WebAdmin

WebRoot/js/zimbraAdmin/accounts/model/ZaAccount.js, WebRoot/js/zimbraAdmin/accounts/view/ZaAccountXFormView.js, WebRoot/js/zimbraAdmin/accounts/view/ZaNewAccountXWizard.js, WebRoot/js/zimbraAdmin/cos/model/ZaCos.js, WebRoot/js/zimbraAdmin/cos/view/ZaCosXFormView.js, WebRoot/js/zimbraAdmin/cos/view/ZaNewCosXWizard.js, WebRoot/messages/ZaMsg.properties, WebRoot/messages/ZaMsg_hr.properties
Bugs(reported for version 9.0.0):
1. Home > Configure > Class of Service > default > Advanced > under "Password" > there is an option "Reject common passwords" (zimbraPasswordBlockCommonEnabled) > if I check it and save it gets unchecked.
2. Home > Manage Accounts > select an account > Advanced > under "Password" > there is an option "Reject common passwords" (zimbraPasswordBlockCommonEnabled) > if I check it and save it gives error "Server error encountered".
Changes:
- Revert all changes made under #70.
- Revert a translation change made under #75.
=> ZBUG-2871: Cant enable "reject common passwords

WebRoot/admin_skins/serenity/skin.css, WebRoot/js/zimbraAdmin/common/Super_XFormItems.js, WebRoot/js/zimbraAdmin/common/ZaSelectMultipleCheckboxXFormItem.js, WebRoot/js/zimbraAdmin/domains/model/ZaDomain.js, WebRoot/js/zimbraAdmin/domains/view/ZaDomainXFormView.js, WebRoot/js/zimbraAdmin/domains/view/ZaNewDomainXWizard.js, WebRoot/js/zimbraAdmin/globalconfig/view/GlobalConfigXFormView.js, WebRoot/js/zimbraAdmin/package/Admin.js
**Issues:**
1. some attributes have been added for Two-factor authentication on https://github.com/Zimbra/zm-mailbox/pull/1519 .
`zimbraTwoFactorAuthMethodAllowed` and `zimbraTwoFactorAuthMethodEnabled` can have multiple values; `app` and `email`. Each method of the settings need to be enabled/disabled on admin console.
However, there is no xform item to support multiple checkboxes in a single setting (attribute). 
2. In CreateDomainRequest, only limited attributes can be set. No other attributes cannot be set in the soap request.
**Changes:**
For 1,
* add the following xform types
* `_SUPER_MULTIPLE_CHECKBOX_`: `accountInherited` (`Reset to COS value` button) is supported. Used in Edit account page.
* `_SUPER_WIZ_MULTIPLE_CHECKBOX_`: same as the above. Used in New account page.
* …
=> ZCS-14111: added xform to support multiple checkboxes in a single setting. Added logic to add attributes to CreateDomainRequest.

WebRoot/js/zimbraAdmin/common/ZaTree.js, WebRoot/messages/ZaMsg.properties, WebRoot/messages/ZaMsg_en_AU.properties
- Added a check _itemClicked method for storage management which evaluates value of storagemanagement from getlicenseinfo and displays error in case it is false or the Storage management extension is not present as the ZaVolume gets initialised and the internal volumes are displayed in case the extension is not present.
=> ZCS-14190: User should get proper error message for creating external storage and creating buckets and volumes from UI when hsm is disabled.

WebRoot/js/zimbraAdmin/common/ZaTree.js, WebRoot/messages/ZaMsg.properties, WebRoot/messages/ZaMsg_en_AU.properties, WebRoot/messages/ZaMsg_en_GB.properties
- changed the error string ERROR_FEATURE_NOT_LICENSED to Your license for this feature has expired or is not valid. Please see Configure - Global Settings - License for more information.
=> ZCS-14347:HSM / S3 restriction based on license status

WebRoot/js/zimbraAdmin/cos/model/ZaCos.js
Adding an ability to set empty value on an attribute which can have multiple values (i.e. cardinality="multi") in CreateCosRequest.
**Issue:**
There is a setting which has multiple checkboxes. When all checkbox of an attribute is unchecked, an empty value should be sent at CreateCosRequest (i.e. `<a n=attr_name></a>`). Currently an empty value is not sent, and then a default value of a cos defined in `defaultCOSValue` is used.
**Change:**
* add an array to set attribute name(s)
* add a logic to set an empty value of the attribute included in the array. It works only on an attribute with cardinality="multi" as it is in `if(mods[aname] instanceof Array) {` block
=> ZCS-15059: add ability to set empty value on multi-value attribute in CreateCosRequest

WebRoot/js/zimbraAdmin/common/ZaTree.js
In case the license is not valid the license is expired or the Feature attribute is disabled in the license, we have to stop the user from accessing that functionality and have to show an error popup on the item clicked.
- Added a blank array licenseCheckArray.(Passing objects into that array through the admin extensions)
- update the itemClicked function for admin extensions.
=> ZCS-15293: License | Disable BackupEnabled API, if license/feature is not activated

WebRoot/js/zimbraAdmin/search/view/ZaSearchField.js
**Issue:**
Ctrl+A key does not work in search field at the top of the page on admin console.
**Root cause:**
`onselectstart` is disabled in a parent div element.
`<div id="_XForm_query" class="dynselect" style="width:100%;" onclick="XFG.cacheGet('_XForm').getItemById('_XForm_query').onClick(event)" onselectstart="return false">`
It is set in the following code:
```
DynSelect_XFormItem.prototype.outputHTML = function (HTMLoutput) {
//...
HTMLoutput.append (
"<div id=",
id,
this.getCssString(),
" onclick=\"",
this.getFormGlobalRef(),
".getItemById('",
this.getId(),
"').onClick(event)\"",
" onselectstart=\"return false\"", <===== HERE
">",
//...
);
```
**Fix:**
* set `onselectstart` to `null` on the search field.
* As `DynSelect_XFormItem` form is used not only on the search field but also …
=> ZBUG-4153: removed onselectstart from search field

WebRoot/js/zimbraAdmin/accounts/model/ZaAccount.js, WebRoot/js/zimbraAdmin/accounts/view/ZaAccountXFormView.js, WebRoot/js/zimbraAdmin/accounts/view/ZaNewAccountXWizard.js
ZCS-13220: Add option in admin console to hide aliases in GAL for the user.
Problem: In Admin Console, provide the **Hide aliases in GAL** option on the Account level.
Solution: Added **Hide aliases in GAL** Checkbox in Account level.
=> ZCS-13220: Add option in admin console to hide aliases in GAL for the user
